[package]
name = "culpa"
version = "0.1.0"
authors = ["Øystein Walle"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gix = "0.44"
rangemap = "1.3.0"

[dev-dependencies]
pretty_assertions = "1.3"
